// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaj9cJ7q6kR6_YaPGx-PFXeLgs2YfOWn8',
    appId: '1:493990809912:web:ffadd82d74cad3ed7531cd',
    messagingSenderId: '493990809912',
    projectId: 'remote-hot-reload',
    authDomain: 'remote-hot-reload.firebaseapp.com',
    databaseURL: 'https://remote-hot-reload-default-rtdb.firebaseio.com',
    storageBucket: 'remote-hot-reload.appspot.com',
    measurementId: 'G-YSQ667VQ99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oeojNfVNQ0-W5wxl6JFxo8yxtz_3MFk',
    appId: '1:493990809912:android:ce5b7b9f0a831fe37531cd',
    messagingSenderId: '493990809912',
    projectId: 'remote-hot-reload',
    databaseURL: 'https://remote-hot-reload-default-rtdb.firebaseio.com',
    storageBucket: 'remote-hot-reload.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4mW5TT8hhi-NRrfTKT8P8sJaiz258zo',
    appId: '1:493990809912:ios:71abc03e468213ea7531cd',
    messagingSenderId: '493990809912',
    projectId: 'remote-hot-reload',
    databaseURL: 'https://remote-hot-reload-default-rtdb.firebaseio.com',
    storageBucket: 'remote-hot-reload.appspot.com',
    iosBundleId: 'com.example.remoteHotReload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT4mW5TT8hhi-NRrfTKT8P8sJaiz258zo',
    appId: '1:493990809912:ios:cc36d1b5d6ad2bf27531cd',
    messagingSenderId: '493990809912',
    projectId: 'remote-hot-reload',
    databaseURL: 'https://remote-hot-reload-default-rtdb.firebaseio.com',
    storageBucket: 'remote-hot-reload.appspot.com',
    iosBundleId: 'com.example.remoteHotReload.RunnerTests',
  );
}
